<?php

namespace VATGER\Auth\Entity;

class Post extends XFCP_Post {
    protected function _preDelete()
    {
        parent::_preDelete(); // TODO: Change the autogenerated stub
    }

    protected function _postDelete()
    {
        parent::_postDelete(); // TODO: Change the autogenerated stub
    }

    protected function postHidden($hardDelete = false)
    {
        parent::postHidden($hardDelete); // TODO: Change the autogenerated stub
    }
}