<?php

namespace VATGER\Auth\Entity;

use VATGER\Auth\Service\VatgerModerationLog\CreatorService;
use XF\Entity\Forum;

class Thread extends XFCP_Thread {
    protected function _preDelete(): void
    {
        /** @var CreatorService $creatorService */
        $creatorService = $this->app()->service(CreatorService::class);

        $creatorService->setHardDeleteDetails($this);
        $creatorService->save();

        parent::_preDelete();
    }

    protected function _postDelete(): void
    {
        $db = $this->db();

        $db->update('xf_vatger_moderation_logs', [
            'thread_id' => null
        ], "thread_id = {$this->thread_id}");

        parent::_postDelete();
    }

    protected function threadMoved(Forum $from, Forum $to): void
    {
        /** @var CreatorService $creatorService */
        $creatorService = $this->app()->service(CreatorService::class);

        $creatorService->setMoveDetails($this, $from, $to);
        $creatorService->save();

        parent::threadMoved($from, $to);
    }

    protected function threadHidden($hardDelete = false): void
    {
        /** @var CreatorService $creatorService */
        $creatorService = $this->app()->service(CreatorService::class);

        $creatorService->setSoftDeleteDetails($this);
        $creatorService->save();

        parent::threadHidden($hardDelete); // TODO: Change the autogenerated stub
    }
}